//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrierAPIsTest_CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingInfoMailroom
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string Carrier { get; set; }
        public string CarrierTrackingNumber { get; set; }
        public Nullable<System.DateTime> CarrierPlannedDeliverDate { get; set; }
        public Nullable<System.DateTime> EstDeliverDate { get; set; }
        public Nullable<System.DateTime> ActDeliverDate { get; set; }
        public string ServiceLevel { get; set; }
        public System.DateTime ShipRequestCreateDate { get; set; }
        public string PackageStatus { get; set; }
        public string ShortBuildingName { get; set; }
        public string ReceiverAddress1 { get; set; }
        public string ReceiverAddress2 { get; set; }
        public string ReceiverCity { get; set; }
        public string ReceiverPostalCode { get; set; }
        public string ReceiverCountryCode { get; set; }
        public string ShipRequestNumber { get; set; }
        public int MaxDeliverPeriod { get; set; }
    }
}
